version: '3.8'

services:
  jungle:
    build: ..
    container_name: jungle
    command: bash -c " cd challenge && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: challenge
      POSTGRES_USER: user
      POSTGRES_DB: challenge
    ports:
      - "5433:5432"
