version: '3.8'

services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: challenge
      POSTGRES_USER: user
      POSTGRES_DB: challenge
    ports:
      - "5433:5432"

  jungle:
    build: .
    container_name: jungle
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
