version: '3.8'

services:
  postgres-db:
    image: postgres
    container_name: challenge_container
    environment:
      POSTGRES_PASSWORD: challenge
      POSTGRES_USER: user
      POSTGRES_DB: challenge
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    container_name: adminer_container
    ports:
      - 8080:8080